#!/bin/bash

function rg_color {
	CURRENT=$1 # non decimal (floored)
	TOTAL=$2 # non decimal
  if (( $TOTAL == 0 )) || [ -z "$TOTAL" ]; then
    TOTAL=100
  fi
	HALF=$(( TOTAL / 2 )) # non decimal (floored)
	RED=255
	GREEN=255
	if [ $CURRENT -gt $HALF ]; then
		# calculate amount of red
		RED=$(( (255 / HALF) * (TOTAL - CURRENT) ))
	else
		# calculate amount of green
		GREEN=$(( (255 / HALF) * (CURRENT) ))
	fi
	RED="$(printf %02X $RED)"
	GREEN="$(printf %02X $GREEN)"
	echo "#$RED${GREEN}00"
}

INFO=$(acpi -b | head -n 2 | tail -1 | sed -rn 's/^.*, (.*?)%, ((.*?):[0-9]{2} )?(.*)$/\1 \3 \4/p')
BATTERY=$(echo $INFO | awk '{print $1}')
#echo "WTF: $(echo $INFO | grep charg)"
#echo "$INFO"

if [ "$(echo $INFO | awk '{print $3}')" != "remaining" ]; then
	REMAIN="+"
  BATTERY_INDICATOR=
  BATTERY=$(echo $INFO | awk '{print $1}')
  if [ -e $BATTERY ];
  then
    BATTERY=100
    echo "test"
  fi
else
	REMAIN=$(echo $INFO | awk '{print $2}')
  if (( $BATTERY > 60 )); then
    BATTERY_INDICATOR=
  elif (( $BATTERY > 30 )); then
    BATTERY_INDICATOR=
  elif (( $BATTERY > 8 )); then
    BATTERY_INDICATOR=
  else
    BATTERY_INDICATOR=
  fi
fi

# $BATTERY
COLOR="$(rg_color $BATTERY 100)"
BATTERY_INFO="$BATTERY_INDICATOR ($REMAIN, $BATTERY%)"

echo -n "full_text:$BATTERY_INFO///"
echo "color:$COLOR"
