#!/bin/bash

# check if muted
if [[ $(amixer sget Master) == *"[off]"* ]]; then
	VOL_ICON=""
  VOLUME="Muted"
else
  VOLUME=$(awk -F "[][]" '/%/ { print $2 }' <(amixer sget Master) | head -n 1)
  if [ $VOLUME \> 50 ]; then
	  VOL_ICON=""
  elif [ $VOLUME \> 1 ]; then
    VOL_ICON=""
  else
    VOL_ICON=""
  fi
fi

echo "full_text:$VOL_ICON $VOLUME"
