#!/bin/bash

# check if muted
if [[ $(amixer sget Master) == *"[off]"* ]]; then
	VOL_ICON=""
  VOLUME="Muted"
else
  VOLUME=$(awk -F "[][]" '/%/ { print $2 }' <(amixer sget Master) | head -n 1)
  VOLUMELEVEL=$(echo "$VOLUME" | sed 's/%//')

  if (( $VOLUMELEVEL > 50 )); then
	  VOL_ICON=""
  elif (( $VOLUMELEVEL > 0 )); then
    VOL_ICON=""
  else
    VOL_ICON=""
  fi
fi

echo "full_text:$VOL_ICON $VOLUME"
